language: node_js

node_js:
  - 7
  - 6
  - 5
  - 4
  - 0.12
  - 0.10

script: "make test-travis"

after_script: "npm install coveralls@2.11.1 && cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"

notifications:
  email:
    - math.nao@outlook.com

